backend:
  name: git-gateway
  branch: main # Branch to update (master by default)

media_folder: 'media' # Folder where user uploaded files should go

# This line should *not* be indented
publish_mode: editorial_workflow

collections:
  - label: Services
    name: services
    files:
      - label: Operación y comercialización
        name: operation
        format: json
        file: 'content/services/operation.json'
        fields:
          - { label: Title, name: title, widget: string }
          - { label: 'Description', name: description, widget: markdown }
          - { label: Image, name: image, widget: image }
          - { label: 'SEO Description', name: seoDescription, widget: text, required: false }
      - label: Finanzas, administración y planeación fiscal
        name: finance
        format: json
        file: 'content/services/finance.json'
        fields:
          - { label: Title, name: title, widget: string }
          - { label: 'Description', name: description, widget: markdown }
          - { label: Image, name: image, widget: image }
          - { label: 'SEO Description', name: seoDescription, widget: text, required: false }
      - label: Capital humano y desarrollo organizacional
        name: capital
        format: json
        file: 'content/services/capital.json'
        fields:
          - { label: Title, name: title, widget: string }
          - { label: 'Description', name: description, widget: markdown }
          - { label: Image, name: image, widget: image }
          - { label: 'SEO Description', name: seoDescription, widget: text, required: false }
      - label: Headhunting
        name: headhunting
        format: json
        file: 'content/services/headhunting.json'
        fields:
          - { label: Title, name: title, widget: string }
          - { label: 'Description', name: description, widget: markdown }
          - { label: Image, name: image, widget: image }
          - { label: 'SEO Description', name: seoDescription, widget: text, required: false }
      - label: Control interno, procesos, medición del riesgo y método COSO.
        name: control
        format: json
        file: 'content/services/control.json'
        fields:
          - { label: Title, name: title, widget: string }
          - { label: 'Description', name: description, widget: markdown }
          - { label: Image, name: image, widget: image }
          - { label: 'SEO Description', name: seoDescription, widget: text, required: false }
      - label: Consejero independiente y gobierno corporativo.
        name: government
        format: json
        file: 'content/services/government.json'
        fields:
          - { label: Title, name: title, widget: string }
          - { label: 'Description', name: description, widget: markdown }
          - { label: Image, name: image, widget: image }
          - { label: 'SEO Description', name: seoDescription, widget: text, required: false }
      - label: Identidad corporativa, impresos y promocionales
        name: identity
        format: json
        file: 'content/services/identity.json'
        fields:
          - { label: Title, name: title, widget: string }
          - { label: 'Description', name: description, widget: markdown }
          - { label: Image, name: image, widget: image }
          - { label: 'SEO Description', name: seoDescription, widget: text, required: false }
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    create: true
    slug: '{{slug}}'
    format: 'json'
    sort: 'published_at:desc'
    fields:
      - { label: Title, name: title, widget: string }
      - { label: 'Published At', name: publishedAt, widget: date, format: 'Do MMM YYYY' }
      - { label: Content, name: content, widget: markdown }
      - { label: 'Featured Image', name: featuredImage, widget: image, required: false }
      - { label: 'SEO Description', name: seoDescription, widget: text, required: false }