backend:
  name: git-gateway
  branch: main # Branch to update (master by default)

media_folder: 'media' # Folder where user uploaded files should go

# This line should *not* be indented
publish_mode: editorial_workflow

collections:
  - label: Services
    name: services
    files:
      - label: General
        name: general
        format: json
        file: 'content/services/operation.json'
        fields:
          - { label: Title, name: title, widget: string }
          - { label: 'Description', name: description, widget: markdown }
          - { label: Image, name: image, widget: image }
          - { label: 'SEO Description', name: seoDescription, widget: text, required: false }
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    create: true
    slug: '{{slug}}'
    format: 'json'
    sort: 'published_at:desc'
    fields:
      - { label: Title, name: title, widget: string }
      - { label: 'Published At', name: publishedAt, widget: date, format: 'Do MMM YYYY' }
      - { label: Content, name: content, widget: markdown }
      - { label: 'Featured Image', name: featuredImage, widget: image, required: false }
      - { label: 'SEO Description', name: seoDescription, widget: text, required: false }